name: Build and Release app

on:
  push:
    branches: [ stable ]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.10'
          channel: 'stable'

      - name: Build Linux
        run: |
          flutter config --enable-linux-desktop
          flutter pub get
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter build linux
      - name: Save linux package
        uses: actions/upload-artifact@v3
        with:
          name: lin
          path: build/linux/x64/release/bundle/*

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.10'
          channel: 'stable'

      - name: Build Windows
        run: |
          flutter config --enable-windows-desktop
          flutter pub get
          flutter build windows
          flutter pub run msix:create --install-certificate false
      - name: Save Windows app
        uses: actions/upload-artifact@v3
        with:
          name: win
          path: build\windows\runner\Release\*

  # build-macos:
  #   runs-on: macos-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Setup flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: '3.7.10'
  #         channel: 'stable'

  #     - name: Build MacOS
  #       run: |
  #         flutter config --enable-macos-desktop
  #         flutter pub get
  #         flutter build macos

  #     - name: Save MacOS app
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: mac
  #         path: build/macos/Build/Products/Release/*

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows] # build-macos
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get all build outputs
        uses: actions/download-artifact@v3
        with:
          path: exec/

      - name: Zip Linux and Windows programs
        run: 7z a -tZip Treboard-linux.zip exec/lin && 7z a -tZip Treboard-win.zip exec/win # && 7z a -tZip Treboard-mac.zip exec/mac

      - name: Display structure of downloaded files
        run: tree exec/

      - name: Create release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Treboard
          tag_name: v0.0.1
          prerelease: true
          generate_release_notes: true
          files: |
            Treboard-linux.zip
            Treboard-win.zip
            exec/win/Treboard.msix
          # Treboard-mac.zip

          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: treboard/treboard
